apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  labels:
    function: app
spec:
  replicas: 3
  selector:
    matchLabels:
      function: app
  template:
    metadata:
      name: mysite-pod
      labels:
        function: app
    spec:
      containers:
      - name: django-container
        image: ghcr.io/weaselsmith/cis-92:milestone-13.0.1
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            httpHeaders:
            - name: host
              value: localhost
        resources:
          limits:
            memory: 512Mi
            cpu: 250m
            ephemeral-storage: 10Mi
          requests:
            memory: 512Mi
            cpu: 250m
            ephemeral-storage: 10Mi
        envFrom:
        - configMapRef:
            name: mysite-config
        - secretRef:
            name: mysite-secret