apiVersion: v1
kind: Pod
metadata:
  name: mysite-pod
  labels:
    function: app
spec:
  volumes:
  - name: db
    persistentVolumeClaim:
        claimName: mysite-data
  containers:
  - name: django-container
    image: ghcr.io/weaselsmith/cis-92:milestone-6.3
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: db
      mountPath: /data
    resources:
      limits:
        memory: 512Mi
        cpu: 250m
        ephemeral-storage: 10Mi
      requests:
        memory: 512Mi
        cpu: 250m
        ephemeral-storage: 10Mi
    envFrom:
    - configMapRef:
        name: mysite-config
    - secretRef:
        name: mysite-secret
