apiVersion: v1
kind: Pod
metadata:
  name: django-pod
  labels:
    function: app
spec:
  containers:
  - name: django-container
    image: ghcr.io/weaselsmith/cis92:milestone-6.3
    ports:
    - containerPort: 8000
    resources:
      limits:
        memory: 512Mi
        cpu: 250m
        ephemeral-storage: 10Mi
      requests:
        memory: 512Mi
        cpu: 250m
        ephemeral-storage: 10Mi
    env:
    - name: STUDENT_NAME
      value: "Noah"
    - name: SITE_NAME
      value: "*"
